test docker build failure

diff --git a/test-migration_ok b/test-migration_ok
--- a/test-migration_ok
+++ b/test-migration_ok
@@ -1,5 +1,8 @@
 #!/bin/bash -eu
 
+# Test that a successful migration will cause a specific file to be
+# created in the shared migation-logs directory.
+
 . ./lib.bash
 setup_standard
 
@@ -12,10 +15,9 @@ confirm_seed_data
 confirm_postgres_version 14
 confirm_backend_running_ok
 
-migrationLogFile="./migration-logs/migrate-postgres-9.6-14.log"
-if ! [[ -f "$migrationLogFile" ]]; then
+if ! [[ -f ./migration-logs/migrate-postgres-9.6-14.completed.ok ]]; then
   log "!!!"
-  log "!!! Migration success flag not found!"
+  log "!!! Migration success flag file not found!"
   log "!!!"
   exit 1
 fi
