check for new success flag

diff --git a/test-migration b/test-migration
--- a/test-migration
+++ b/test-migration
@@ -212,6 +212,11 @@ confirm_seed_data
 confirm_postgres_version 14
 confirm_backend_running_ok
 
-grep '[odk-migrate-postgres] Migration complete.' ./migration-logs/migrate-postgres-9.6-14.log
+if ! [[ -f ./migration-logs/migrate-postgres-9.6-14.completed.ok ]]; then
+  log "!!!"
+  log "!!! Migration success flag not found!"
+  log "!!!"
+  exit 1
+fi
 
 log "Test passed OK!"
