no-space: test failure

diff --git a/test-migration_no-space-destination b/test-migration_no-space-destination
--- a/test-migration_no-space-destination
+++ b/test-migration_no-space-destination
@@ -217,8 +217,15 @@ docker-compose up --remove-orphans --detach
 wait_for_service_container
 
 confirm_postgres_version "" # i.e. not running
-cat ./migration-logs/migrate-postgres-9.6-14.log
-echo "TODO should test file contents here."
-exit 1
+migrationLogFile="./migration-logs/migrate-postgres-9.6-14.log"
+if ! grep -E 'UTC .* FATAL: .*: No space left on device$' "$migrationLogFile"; then
+  log "------------------ $migrationLogFile ------------------"
+  cat "$migrationLogFile"
+  log "-------------------------------------------------------"
+  log "!!!"
+  log "!!! Migration failed for unexpected reason!  Please review logs above."
+  log "!!!"
+  exit 1
+fi
 
 log "Test passed OK!"
